- name: Add APT key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add APT repository
  become: yes
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
    update_cache: yes

- name: Install Visual Studio Code
  become: yes
  apt:
    name: code
    state: latest
