- hosts: [localhost]
  connection: local
  vars_files:
    - vars/dirs.yml
  vars:
    font_awesome_version: 5.13.0
    slack_version: 4.4.2
  tasks:
    - import_tasks: tasks/prerequisites.yml
    - import_role:
        name: docker
      tags: docker
    - import_role:
        name: apt
      tags: apt
    - import_role:
        name: vscode
      tags: vscode
    - import_role:
        name: sway
      tags: sway
    - import_role:
        name: slack
      tags: slack
